const DEFAULT_PRODUCT_SEED = [
  {
    name: "Oraimo Maxi Watch",
    description: "Smart wearable with advanced battery life.",
    categories: ["flights", "essentials"],
    price: 2631.9,
    oldPrice: 4900,
    badge: "-47%",
    color: "linear-gradient(135deg,#e8f0ff,#d0dcff)",
    stockQty: 25,
    isActive: true,
    imageUrl: "product-imgs/1.jpg",
  },
  {
    name: "Oraimo Power Bank Lite",
    description: "Portable, durable power backup for daily use.",
    categories: ["flights", "essentials"],
    price: 136.9,
    oldPrice: 300,
    badge: "-56%",
    badgeType: "sale",
    color: "linear-gradient(135deg,#e8f0ff,#d0dcff)",
    stockQty: 10,
    isActive: true,
    imageUrl: "product-imgs/magpower-15-opb-7102w-1.webp",
  },
  {
    name: "Oraimo Lite Earphones",
    description: "Wireless comfort with crisp sound output.",
    categories: ["lounge", "flights"],
    price: 126.98,
    oldPrice: 240,
    badge: "-47%",
    badgeType: "sale",
    color: "linear-gradient(135deg,#fff0f5,#ffd6e8)",
    stockQty: 18,
    isActive: true,
    imageUrl: "product-imgs/oraimo-BoomPop-Pro-OHP-917-wireless-headphones-GREY.webp",
  },
  {
    name: "Oraimo CleanSip Faucet",
    description: "Smart faucet accessory for cleaner water flow.",
    categories: ["lounge", "insurance"],
    price: 217,
    oldPrice: 400,
    badge: "-42%",
    badgeType: "sale",
    color: "linear-gradient(135deg,#fff8e8,#ffecc0)",
    stockQty: 60,
    isActive: true,
    imageUrl: "product-imgs/wireless-earphones-spacebuds-neo-plus-otw-323p-black.webp",
  },
  {
    name: "Oraimo NutriFry Max Air",
    description: "Efficient air-fryer technology for quick meals.",
    categories: ["upgrades", "essentials"],
    price: 1078.92,
    oldPrice: 1800,
    badge: "-39%",
    badgeType: "sale",
    color: "linear-gradient(135deg,#f0e8ff,#dcc0ff)",
    stockQty: 50,
    isActive: true,
    imageUrl: "product-imgs/oraimo-watch-muse-OSW-831N-4.webp",
  },
  {
    name: "Oraimo Smart Trimmer",
    description: "Precision grooming with long-lasting blades.",
    categories: ["upgrades", "insurance"],
    price: 183.89,
    oldPrice: 350,
    badge: "-47%",
    badgeType: "sale",
    color: "linear-gradient(135deg,#e8fff5,#c0f5e0)",
    stockQty: 20,
    isActive: true,
    imageUrl: "product-imgs/africa-en-galaxy-s26-ultra-s948-sm-s948bzvoafb-thumb-551361084.webp",
  },
  {
    name: "Oraimo Wireless Charger",
    description: "Fast wireless charging for multiple devices.",
    categories: ["essentials", "flights"],
    price: 183.89,
    oldPrice: 350,
    badge: "-47%",
    badgeType: "sale",
    color: "linear-gradient(135deg,#e8f5ff,#c0e0ff)",
    stockQty: 100,
    isActive: true,
    imageUrl: "product-imgs/AI-appliances_v21.avif",
  },
  {
    name: "Pepsodent Tooth Paste",
    description: "Daily oral care essential for the whole family.",
    categories: ["insurance", "essentials"],
    price: 2631.9,
    oldPrice: 4900,
    badge: "-47%",
    badgeType: "sale",
    color: "linear-gradient(135deg,#e8ffee,#c0f0ce)",
    stockQty: 80,
    isActive: true,
    imageUrl: "product-imgs/personal-care/36024a.jpg",
  },
  {
    name: "Close Up Tooth Paste",
    description: "Fresh breath toothpaste with active formula.",
    categories: ["insurance", "essentials"],
    price: 136.9,
    oldPrice: 300,
    badge: "-56%",
    badgeType: "sale",
    color: "linear-gradient(135deg,#ffe8e8,#ffc0c0)",
    stockQty: 70,
    isActive: true,
    imageUrl: "product-imgs/personal-care/67728a.jpg",
  },
  {
    name: "Kel Mouth Wash",
    description: "Deep-clean mouthwash for complete care.",
    categories: ["insurance", "essentials"],
    price: 126.98,
    oldPrice: 240,
    badge: "-47%",
    badgeType: "sale",
    color: "linear-gradient(135deg,#f6e8ff,#e6c7ff)",
    stockQty: 70,
    isActive: true,
    imageUrl: "product-imgs/personal-care/70100a.jpg",
  },
  {
    name: "Oral B Tooth Brush",
    description: "Durable toothbrush designed for comfort.",
    categories: ["insurance", "essentials"],
    price: 217,
    oldPrice: 400,
    badge: "-42%",
    badgeType: "sale",
    color: "linear-gradient(135deg,#e8f7ff,#c7e9ff)",
    stockQty: 70,
    isActive: true,
    imageUrl: "product-imgs/personal-care/94947a.jpg",
  },
];

const DEFAULT_DEALS_SETTINGS = [
  {
    id: "deal-1",
    name: "Oraimo Brand Day",
    timerSeconds: 80200,
    seeMoreFilter: "flights",
    sourceCategory: "flights",
    sourceCategories: ["flights", "lounge", "upgrades", "essentials"],
    maxItems: 8,
    isActive: true,
    productIds: [],
  },
  {
    id: "deal-2",
    name: "Personal Care Day",
    timerSeconds: 21600,
    seeMoreFilter: "insurance",
    sourceCategory: "insurance",
    sourceCategories: ["insurance", "essentials"],
    maxItems: 8,
    isActive: true,
    productIds: [],
  },
];

module.exports = {
  DEFAULT_PRODUCT_SEED,
  DEFAULT_DEALS_SETTINGS,
};
